# Generated by Django 5.0.1 on 2024-06-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='text',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
